import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Nunito } from "next/font/google";
import { Toaster } from 'react-hot-toast';

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

import './globals.css'
import { ThemeProvider } from '../components/theme-provider';

// const inter = Inter({ subsets: ['latin'] })

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Guylaine',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='fr'>
      <body className={font.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main>{children}</main>
          <Toaster position='top-right' />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}