import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Nunito } from "next/font/google";

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='fr'>
      <body className={font.className}>
        <Navbar />
        <main>{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  )
}